spring:
  application:
    name: account-cmd
  data:
    mongodb:
      host: mongodb
      database: bankAccount
      authentication-database: admin
  kafka:
    producer:
      bootstrap-servers: bitnami-kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer      
  output:
    ansi:
      enabled: ALWAYS
  keycloak:
      server-url: http://keycloak-server:8080
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.greeta.net/realms/movie-realm
          jwk-set-uri: ${spring.keycloak.server-url}/realms/movie-realm/protocol/openid-connect/certs

kafka-config:
  bootstrap-servers: bitnami-kafka:9092
  num-of-partitions: 1
  replication-factor: 1

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.StringDeserializer
  value-serializer-class: org.springframework.kafka.support.serializer.JsonDeserializer
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 5         


logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    org.springframework.cloud.kubernetes: TRACE
    org.springframework.security: DEBUG

info:
  system: Account Command Service

jwt:
  auth:
    converter:
      resource-id: movie-app
      principal-attribute: preferred_username

management:
  endpoints:
    web:
      exposure:
        include: bindings, configprops, env, flyway, functions, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


server:
  forward-headers-strategy: framework

openapi:
  oauthflow:
    authServerUrl: https://keycloak.greeta.net
    realm: movie-realm